app:
  env: development
  debug: true
server:
  port: 6799
db:
  host: localhost
  port: 5432
  user: postgres
  password: secret
  connection_string: "string"
  max_open_connections: 25
  max_idle_connections: 5